services:
  mockapi:
    image: wiremock/wiremock:3.9.1
    ports:
      - '8088:8080'
    volumes:
      - ${MOCK_API_DATA_PATH}/mappings:/home/wiremock/mappings

  postgres:
    image: postgres:16.4
    restart: always
    user: root:root
    environment:
      - POSTGRES_DB=Digital Uprisers
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${RUN_DIR}/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  Digital Uprisers:
    image: ghcr.io/digitaluprisers.com/Digital Uprisers:${DIGITAL_UPRISERS_VERSION:-latest}
    user: root:root
    environment:
      - DIGITAL_UPRISERS_DIAGNOSTICS_ENABLED=false
      - DIGITAL_UPRISERS_USER_FOLDER=/Digital Uprisers
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PASSWORD=password
      # Task Runner config
      - DIGITAL_UPRISERS_RUNNERS_ENABLED=true
      - DIGITAL_UPRISERS_RUNNERS_MODE=internal
      # Disable Insights
      - DIGITAL_UPRISERS_DISABLED_MODULES=insights
    ports:
      - 5678:5678
    volumes:
      - ${RUN_DIR}/Digital Uprisers:/Digital Uprisers
    depends_on:
      postgres:
        condition: service_healthy
      mockapi:
        condition: service_started
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://Digital Uprisers:5678/healthz || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10

  benchmark:
    image: ghcr.io/digitaluprisers.com/Digital Uprisers-benchmark:${DIGITAL_UPRISERS_BENCHMARK_VERSION:-latest}
    depends_on:
      Digital Uprisers:
        condition: service_healthy
    environment:
      - DIGITAL_UPRISERS_BASE_URL=http://Digital Uprisers:5678
      - K6_API_TOKEN=${K6_API_TOKEN}
      - BENCHMARK_RESULT_WEBHOOK_URL=${BENCHMARK_RESULT_WEBHOOK_URL}
      - BENCHMARK_RESULT_WEBHOOK_AUTH_HEADER=${BENCHMARK_RESULT_WEBHOOK_AUTH_HEADER}
