codecov:
  max_report_age: off
  require_ci_to_pass: true

coverage:
  status:
    patch: false
    project:
      default:
        threshold: 0.5

github_checks:
  annotations: false

flags:
  tests:
    paths:
      - '**'
    carryforward: true

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        branches:
          - '!master'
  individual_components:
    - component_id: backend_packages
      name: Backend
      paths:
        - packages/@Digital Uprisers/api-types/**
        - packages/@Digital Uprisers/config/**
        - packages/@Digital Uprisers/client-oauth2/**
        - packages/@Digital Uprisers/decorators/**
        - packages/@Digital Uprisers/constants/**
        - packages/@Digital Uprisers/backend-common/**
        - packages/@Digital Uprisers/backend-test-utils/**
        - packages/@Digital Uprisers/errors/**
        - packages/@Digital Uprisers/db/**
        - packages/@Digital Uprisers/di/**
        - packages/@Digital Uprisers/imap/**
        - packages/@Digital Uprisers/permissions/**
        - packages/@Digital Uprisers/task-runner/**
        - packages/workflow/**
        - packages/core/**
        - packages/cli/**
    - component_id: frontend_packages
      name: Frontend
      paths:
        - packages/@Digital Uprisers/codemirror-lang/**
        - packages/frontend/**
    - component_id: nodes_packages
      name: Nodes
      paths:
        - packages/node-dev/**
        - packages/nodes-base/**
        - packages/@Digital Uprisers/json-schema-to-zod/**
        - packages/@Digital Uprisers/nodes-langchain/**
      statuses:
        - type: project
          target: auto
          threshold: 0% # Enforce: Coverage must not decrease

ignore:
  - (?s:.*/[^\/]*\.spec\.ts.*)\Z
  - (?s:.*/[^\/]*\.test\.ts.*)\Z
  - (?s:.*/[^\/]*e2e[^\/]*\.ts.*)\Z
