services:
  mockapi:
    image: wiremock/wiremock:3.9.1
    ports:
      - '8088:8080'
    volumes:
      - ${MOCK_API_DATA_PATH}/mappings:/home/wiremock/mappings

  redis:
    image: redis:6.2.14-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s

  postgres:
    image: postgres:16.4
    user: root:root
    restart: always
    environment:
      - POSTGRES_DB=Digital Uprisers
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${RUN_DIR}/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

  Digital Uprisers_worker1:
    image: ghcr.io/digitaluprisers.com/Digital Uprisers:${DIGITAL_UPRISERS_VERSION:-latest}
    user: root:root
    environment:
      - DIGITAL_UPRISERS_DIAGNOSTICS_ENABLED=false
      - DIGITAL_UPRISERS_USER_FOLDER=/Digital Uprisers/worker1
      - DIGITAL_UPRISERS_ENCRYPTION_KEY=${DIGITAL_UPRISERS_ENCRYPTION_KEY}
      # Queue mode config
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - DIGITAL_UPRISERS_CONCURRENCY_PRODUCTION_LIMIT=10
      # DB config
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PASSWORD=password
      # Task Runner config
      - DIGITAL_UPRISERS_RUNNERS_ENABLED=true
      - DIGITAL_UPRISERS_RUNNERS_MODE=internal
      # Enable Insights
      - DIGITAL_UPRISERS_ENABLED_MODULES=insights
    command: worker
    volumes:
      - ${RUN_DIR}/Digital Uprisers-worker1:/Digital Uprisers
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://Digital Uprisers_worker1:5678/healthz || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10

  Digital Uprisers_worker2:
    image: ghcr.io/digitaluprisers.com/Digital Uprisers:${DIGITAL_UPRISERS_VERSION:-latest}
    user: root:root
    environment:
      - DIGITAL_UPRISERS_DIAGNOSTICS_ENABLED=false
      - DIGITAL_UPRISERS_USER_FOLDER=/Digital Uprisers/worker2
      - DIGITAL_UPRISERS_ENCRYPTION_KEY=${DIGITAL_UPRISERS_ENCRYPTION_KEY}
      # Queue mode config
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - DIGITAL_UPRISERS_CONCURRENCY_PRODUCTION_LIMIT=10
      # DB config
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PASSWORD=password
      # Task Runner config
      - DIGITAL_UPRISERS_RUNNERS_ENABLED=true
      - DIGITAL_UPRISERS_RUNNERS_MODE=internal
      # Enable Insights
      - DIGITAL_UPRISERS_ENABLED_MODULES=insights
    command: worker
    volumes:
      - ${RUN_DIR}/Digital Uprisers-worker2:/Digital Uprisers
    depends_on:
      # We let the worker 1 start first so it can run the DB migrations
      Digital Uprisers_worker1:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://Digital Uprisers_worker2:5678/healthz || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10

  Digital Uprisers:
    image: ghcr.io/digitaluprisers.com/Digital Uprisers:${DIGITAL_UPRISERS_VERSION:-latest}
    user: root:root
    environment:
      - DIGITAL_UPRISERS_DIAGNOSTICS_ENABLED=false
      - DIGITAL_UPRISERS_USER_FOLDER=/Digital Uprisers/main
      - DIGITAL_UPRISERS_ENCRYPTION_KEY=${DIGITAL_UPRISERS_ENCRYPTION_KEY}
      # Queue mode config
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      # DB config
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PASSWORD=password
      # Task Runner config
      - DIGITAL_UPRISERS_RUNNERS_ENABLED=true
      - DIGITAL_UPRISERS_RUNNERS_MODE=internal
      # Enable Insights
      - DIGITAL_UPRISERS_ENABLED_MODULES=insights
    ports:
      - 5678:5678
    volumes:
      - ${RUN_DIR}/Digital Uprisers-main:/Digital Uprisers
    depends_on:
      Digital Uprisers_worker1:
        condition: service_healthy
      Digital Uprisers_worker2:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mockapi:
        condition: service_started
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://Digital Uprisers:5678/healthz || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10

  benchmark:
    image: ghcr.io/digitaluprisers.com/Digital Uprisers-benchmark:${DIGITAL_UPRISERS_BENCHMARK_VERSION:-latest}
    depends_on:
      Digital Uprisers:
        condition: service_healthy
    environment:
      - DIGITAL_UPRISERS_BASE_URL=http://Digital Uprisers:5678
      - K6_API_TOKEN=${K6_API_TOKEN}
      - BENCHMARK_RESULT_WEBHOOK_URL=${BENCHMARK_RESULT_WEBHOOK_URL}
      - BENCHMARK_RESULT_WEBHOOK_AUTH_HEADER=${BENCHMARK_RESULT_WEBHOOK_AUTH_HEADER}
